# Generated by Django 3.0.5 on 2020-05-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interrupt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3)),
                ('call_number', models.CharField(max_length=40)),
                ('categories', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=200)),
                ('registers_json', models.CharField(max_length=2000)),
                ('sections_json', models.CharField(max_length=5000)),
            ],
        ),
    ]
