# Generated by Django 3.0.5 on 2020-05-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ralf_explorer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interrupt',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
